
version: "3"
services:
  postgres:
    container_name: mtas-postgres
    image: postgres:latest
    ports:
    - "5434:5432"
    env_file:
    - docker.env
    networks:
    - postgres
 
networks:
  postgres:
    driver: bridge